/**
 * The QR encoder, checked against codes made by something else entirely.
 *
 * A QR encoder is the kind of thing that is either exactly right or completely
 * useless, and it cannot tell you which: every stage produces plausible-looking
 * squares. So the expected values below are not ones this code produced and were then
 * blessed. They were read out of codes generated by Apple's own encoder, and every
 * matrix this file builds was photographed back by Apple's own detector during
 * development, across all ten versions at both sides of each capacity boundary.
 *
 * Three real bugs were caught that way, and none would have shown up in any test
 * written from the same understanding that wrote the code:
 *
 * - The format information runs most significant bit first. Backwards, every other
 *   part is correct and nothing on earth can read the result.
 * - The generator polynomial was being built back to front, so the data codewords came
 *   out perfect and the error correction was noise. A scanner sees a damaged code.
 * - The padding began with whichever pad byte the parity happened to land on. Scanners
 *   do not care, because the length says where the text ends; only another encoder's
 *   output, lined up beside it, ever shows the difference.
 *
 * It lives in the server's test folder because that is where `bun test` looks. The
 * encoder itself is the dashboard's, and has no server in it.
 */
import { describe, expect, test } from 'bun:test';
import { encodeData, encodeQr, qrSvg } from '../../web/src/lib/qr.ts';

function hex(codewords: number[]): string {
  return codewords.map((byte) => byte.toString(16).padStart(2, '0')).join(' ');
}

describe('codewords, against another encoder', () => {
  test('a short address', () => {
    expect(hex(encodeData('http://a.b', 1))).toBe(
      '40 a6 87 47 47 03 a2 f2 f6 12 e6 20 ec 11 ec 11 dd 86 ed 19 42 06 d2 01 b2 9a',
    );
  });

  test('a free subdomain', () => {
    expect(hex(encodeData('https://x.duckdns.org', 2))).toBe(
      '41 56 87 47 47 07 33 a2 f2 f7 82 e6 47 56 36 b6 46 e7 32 e6 f7 26 70 ec 11 ec 11 ec ' +
        'fc c8 52 4c e5 72 e3 59 80 66 a8 26 34 d7 b0 f2',
    );
  });

  test('an address with a path and a query, which is where blocks start splitting', () => {
    expect(hex(encodeData('https://shop-web.example.com', 3)).split(' ').slice(44).join(' ')).toBe(
      '02 26 45 8d 29 ca cd ae 8d f5 84 de 1d e1 9c b3 10 8e 76 5a ae d5 3b e5 57 b1',
    );
  });

  test('the padding starts with the first pad byte, not whichever the parity lands on', () => {
    // A scanner never notices this: the length says where the text stops, so the
    // padding is thrown away unread. The only thing that ever sees it is another
    // encoder's output, side by side. `x.duckdns.org` above is the case that catches
    // it, because its data ends on an odd byte.
    const codewords = encodeData('https://x.duckdns.org', 2);
    expect(codewords.slice(23, 28)).toEqual([0xec, 0x11, 0xec, 0x11, 0xec]);
  });
});

/**
 * The blocks, checked by arithmetic rather than against a reference.
 *
 * Every version from 8 up splits the data into blocks of two different sizes and
 * interleaves them, and getting that wrong produces output where every byte is present
 * and in the wrong place. Rather than trust a transcribed table, this takes the encoder
 * at its word, pulls the blocks back apart, and asks the only question that has a
 * definite answer: is each one actually a valid Reed-Solomon codeword?
 *
 * It is a real check because a codeword's syndromes are zero for reasons that have
 * nothing to do with how the error correction was computed. Interleave wrongly, split
 * wrongly, or get the generator polynomial backwards, and they are not zero.
 */
describe('blocks and interleaving', () => {
  const EXP = new Uint8Array(512);
  const LOG = new Uint8Array(256);
  {
    let x = 1;
    for (let i = 0; i < 255; i++) {
      EXP[i] = x;
      LOG[x] = i;
      x <<= 1;
      if (x & 0x100) x ^= 0x11d;
    }
    for (let i = 255; i < 512; i++) EXP[i] = EXP[i - 255]!;
  }
  const mul = (a: number, b: number) => (a === 0 || b === 0 ? 0 : EXP[LOG[a]! + LOG[b]!]!);

  /** Per version: EC codewords per block, then [blockCount, dataCodewords] groups. */
  const LAYOUT: Record<number, [number, [number, number][]]> = {
    1: [10, [[1, 16]]],
    5: [24, [[2, 43]]],
    6: [16, [[4, 27]]],
    8: [
      22,
      [
        [2, 38],
        [2, 39],
      ],
    ],
    10: [
      26,
      [
        [4, 43],
        [1, 44],
      ],
    ],
  };

  for (const [version, [ecPerBlock, groups]] of Object.entries(LAYOUT)) {
    test(`version ${version}: every block is a valid codeword`, () => {
      const total = groups.reduce((sum, [count, size]) => sum + count * size, 0);
      const text = `https://a.example.com/${'x'.repeat(300)}`.slice(0, Math.min(total - 3, 213));
      const stream = encodeData(text, Number(version));

      const sizes = groups.flatMap(([count, size]) => new Array<number>(count).fill(size));
      expect(stream.length).toBe(total + sizes.length * ecPerBlock);

      // Undo the interleaving: data first, longest-block-last, then the EC.
      const data: number[][] = sizes.map(() => []);
      let at = 0;
      for (let i = 0; i < Math.max(...sizes); i++) {
        for (let b = 0; b < sizes.length; b++) {
          if (i < sizes[b]!) data[b]!.push(stream[at++]!);
        }
      }
      const ec: number[][] = sizes.map(() => []);
      for (let i = 0; i < ecPerBlock; i++) {
        for (let b = 0; b < sizes.length; b++) ec[b]!.push(stream[at++]!);
      }
      expect(at).toBe(stream.length);

      for (let b = 0; b < sizes.length; b++) {
        const codeword = [...data[b]!, ...ec[b]!];
        // A Reed-Solomon codeword vanishes at each of the generator's roots.
        for (let i = 0; i < ecPerBlock; i++) {
          let syndrome = 0;
          for (const byte of codeword) syndrome = mul(syndrome, EXP[i]!) ^ byte;
          expect(syndrome).toBe(0);
        }
      }
    });
  }
});

describe('the finished square', () => {
  test('picks the smallest version the text fits in', () => {
    // 17 + 4v modules a side. Fourteen bytes is all of version 1.
    expect(encodeQr('x'.repeat(14)).length).toBe(21);
    expect(encodeQr('x'.repeat(15)).length).toBe(25);
    expect(encodeQr('x'.repeat(26)).length).toBe(25);
    expect(encodeQr('x'.repeat(27)).length).toBe(29);
  });

  test('goes up to 213 characters, and says so rather than producing rubbish', () => {
    expect(encodeQr('x'.repeat(213)).length).toBe(57);
    expect(() => encodeQr('x'.repeat(214))).toThrow('too long');
  });

  test('has its three finder patterns', () => {
    const m = encodeQr('https://shop-web.example.com');
    const size = m.length;
    for (const [row, col] of [
      [0, 0],
      [0, size - 7],
      [size - 7, 0],
    ] as const) {
      // The ring is dark, the gap inside it is light, and the middle is dark again.
      expect(m[row]![col]).toBe(true);
      expect(m[row + 1]![col + 1]).toBe(false);
      expect(m[row + 2]![col + 2]).toBe(true);
      expect(m[row + 3]![col + 3]).toBe(true);
    }
  });

  test('has its timing patterns, which alternate', () => {
    const m = encodeQr('https://shop-web.example.com');
    for (let i = 8; i < m.length - 8; i++) {
      expect(m[6]![i]).toBe(i % 2 === 0);
      expect(m[i]![6]).toBe(i % 2 === 0);
    }
  });

  test('has the module that is always dark', () => {
    const m = encodeQr('https://shop-web.example.com');
    expect(m[m.length - 8]![8]).toBe(true);
  });

  test('the format information reads back as level M and a real mask', () => {
    const m = encodeQr('https://shop-web.example.com');
    // Read the copy around the top-left finder, most significant bit first.
    const bits: number[] = [];
    for (let i = 0; i <= 5; i++) bits.push(m[8]![i] ? 1 : 0);
    bits.push(m[8]![7] ? 1 : 0, m[8]![8] ? 1 : 0, m[7]![8] ? 1 : 0);
    for (let i = 9; i <= 14; i++) bits.push(m[14 - i]![8] ? 1 : 0);

    let value = 0;
    for (const bit of bits) value = (value << 1) | bit;
    const cleared = value ^ 0b101010000010010;

    expect(cleared >> 13).toBe(0b00); // Level M.
    expect((cleared >> 10) & 7).toBeLessThan(8); // A mask that exists.
    // And the ten check bits are consistent, which is what a scanner verifies first.
    const data = cleared >> 10;
    let bch = data << 10;
    for (let i = 4; i >= 0; i--) {
      if ((bch >> (10 + i)) & 1) bch ^= 0b10100110111 << i;
    }
    expect((cleared & 0x3ff) >>> 0).toBe(bch >>> 0);
  });

  test('the second copy of the format information says the same thing', () => {
    // Not decoration: it is what a scanner falls back on when a code is scuffed.
    const m = encodeQr('https://shop-web.example.com');
    const size = m.length;

    const first: number[] = [];
    for (let i = 0; i <= 5; i++) first.push(m[8]![i] ? 1 : 0);
    first.push(m[8]![7] ? 1 : 0, m[8]![8] ? 1 : 0, m[7]![8] ? 1 : 0);
    for (let i = 9; i <= 14; i++) first.push(m[14 - i]![8] ? 1 : 0);

    const second: number[] = [];
    for (let i = 0; i <= 6; i++) second.push(m[size - 1 - i]![8] ? 1 : 0);
    for (let i = 7; i <= 14; i++) second.push(m[8]![size - 15 + i] ? 1 : 0);

    expect(second).toEqual(first);
  });

  test('every version from 1 to 10 comes out the right size and is stable', () => {
    const sizes = new Set<number>();
    for (const length of [10, 20, 40, 60, 80, 100, 120, 150, 175, 210]) {
      const text = `https://a.example.com/${'x'.repeat(Math.max(0, length - 22))}`.slice(0, length);
      const m = encodeQr(text);
      sizes.add(m.length);
      expect(m.length % 4).toBe(1); // 17 + 4v is always 1 mod 4.
      // Same input, same output. A random mask choice would be a code that changes
      // every render, which looks broken even when it scans.
      expect(encodeQr(text)).toEqual(m);
    }
    expect(sizes.size).toBe(10);
  });
});

describe('as an SVG', () => {
  test('is self-contained, with no request to anywhere', () => {
    const svg = qrSvg('https://shop-web.example.com');
    expect(svg).toStartWith('<svg');
    expect(svg).toContain('viewBox');
    // The whole point: nothing here reaches out to an online generator, which would
    // tell somebody else's server every address on this machine. The one http in
    // there is the SVG namespace, which is an identifier and not somewhere to go.
    expect(svg).not.toContain('<image');
    expect(svg).not.toContain('href');
    expect(svg.match(/https?:\/\//g)).toEqual(['http://']);
  });

  test('leaves a quiet zone, because a code with no margin does not scan', () => {
    const svg = qrSvg('https://shop-web.example.com', { margin: 4 });
    const modules = encodeQr('https://shop-web.example.com').length;
    expect(svg).toContain(`viewBox="0 0 ${modules + 8} ${modules + 8}"`);
  });
});
