#!/usr/bin/env bun
import { readdirSync, statSync } from 'node:fs';
import { join, relative, resolve } from 'node:path';
/**
 * Production build:
 *   1. vite build            → apps/web/dist
 *   2. generate assets.ts    → `with { type: 'file' }` imports so Bun embeds the SPA
 *   3. bun build --compile   → a single static executable
 *
 * The generated assets file is restored to its committed placeholder afterwards so
 * a build never leaves the working tree dirty.
 */
import { $ } from 'bun';

const root = resolve(import.meta.dir, '..');
const webDist = join(root, 'apps/web/dist');
const generatedFile = join(root, 'apps/server/src/generated/assets.ts');

const PLACEHOLDER = `/**
 * Placeholder, \`scripts/build.ts\` rewrites this file with \`with { type: 'file' }\`
 * imports for every file in apps/web/dist, so the SPA is baked into the binary.
 * In development the map stays empty and the server proxies to Vite instead.
 */
export const assets: Record<string, string> = {};
`;

/**
 * The `-musl` pair are for Alpine and anything else not built on glibc. Bun's normal
 * Linux builds link against glibc, so on Alpine they do not merely misbehave, they do
 * not start at all: the shell reports "not found" for a file that is plainly there,
 * which is the least helpful error in computing.
 */
const targets: Record<string, string> = {
  'linux-x64': 'bun-linux-x64',
  'linux-arm64': 'bun-linux-arm64',
  'linux-x64-musl': 'bun-linux-x64-musl',
  'linux-arm64-musl': 'bun-linux-arm64-musl',
  'darwin-x64': 'bun-darwin-x64',
  'darwin-arm64': 'bun-darwin-arm64',
};

function walk(dir: string, out: string[] = []): string[] {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) walk(full, out);
    else out.push(full);
  }
  return out;
}

function generateAssetManifest(): number {
  const files = walk(webDist).sort();
  const lines: string[] = [
    '// GENERATED by scripts/build.ts, do not edit. Restored to a placeholder after each build.',
  ];
  const entries: string[] = [];

  files.forEach((file, index) => {
    const urlPath = `/${relative(webDist, file).split(/[\\/]/).join('/')}`;
    const importPath = relative(join(root, 'apps/server/src/generated'), file)
      .split(/[\\/]/)
      .join('/');
    lines.push(`import a${index} from '${importPath}' with { type: 'file' };`);
    entries.push(`  ${JSON.stringify(urlPath)}: a${index},`);
  });

  lines.push('', 'export const assets: Record<string, string> = {', ...entries, '};', '');
  Bun.write(generatedFile, lines.join('\n'));
  return files.length;
}

async function main() {
  const args = process.argv.slice(2);
  const targetKey = args.find((a) => a.startsWith('--target='))?.split('=')[1];
  const outFile = args.find((a) => a.startsWith('--out='))?.split('=')[1];

  const bunTarget = targetKey ? targets[targetKey] : undefined;
  if (targetKey && !bunTarget) {
    console.error(`Unknown target "${targetKey}". Known: ${Object.keys(targets).join(', ')}`);
    process.exit(1);
  }

  console.log('→ building the dashboard');
  await $`bun run --cwd apps/web build`;

  const count = generateAssetManifest();
  console.log(`→ embedding ${count} dashboard files`);

  const output = outFile ?? (targetKey ? `derailed-${targetKey}` : 'derailed');
  // Bun's bundler inlines process.env.NODE_ENV, and defaults it to "development".
  const nodeEnv = 'process.env.NODE_ENV="production"';
  try {
    console.log(`→ compiling ${output}${bunTarget ? ` for ${bunTarget}` : ''}`);
    if (bunTarget) {
      await $`bun build apps/server/src/index.ts --compile --minify --define ${nodeEnv} --target=${bunTarget} --outfile ${output}`;
    } else {
      await $`bun build apps/server/src/index.ts --compile --minify --define ${nodeEnv} --outfile ${output}`;
    }
  } finally {
    await Bun.write(generatedFile, PLACEHOLDER);
  }

  const size = statSync(output).size;
  console.log(`\n✓ ${output}, ${(size / 1024 / 1024).toFixed(1)} MB`);
}

await main();
